name: 'Build APK'
description: 'assembleDebug'
runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17.0.10'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        APP_KEYSTORE_KEY_ALIAS: ${{ secrets.APP_KEYSTORE_KEY_ALIAS }}
        APP_KEYSTORE_KEY_PASSWORD: ${{ secrets.APP_KEYSTORE_KEY_PASSWORD }}
        APP_KEYSTORE_STORE_PASSWORD: ${{ secrets.APP_KEYSTORE_STORE_PASSWORD }}
        CLICKUP_CLIENT_SECRET: ${{ secrets.CLICKUP_CLIENT_SECRET }}
        CLICKUP_CLIENT_ID: ${{ secrets.CLICKUP_CLIENT_ID }}
      run: ./gradlew :gtd:assembleDebug
