name: Build APK

on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
    secrets:
      APP_KEYSTORE_KEY_ALIAS:
        required: false
      APP_KEYSTORE_KEY_PASSWORD:
        required: false
      APP_KEYSTORE_STORE_PASSWORD:
        required: false
      CLICKUP_CLIENT_SECRET:
        required: false
      CLICKUP_CLIENT_ID:
        required: false
jobs:
  build-apk:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17.0.10'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create environment file from secrets
        run: |
          echo '${{ toJson(secrets) }}' | jq -r 'to_entries | .[] | "\(.key)=\"\(.value)\""' > ci.env
          echo "Secret keys found:"
          echo '${{ toJson(secrets) }}' | jq -r 'keys_unsorted | .[]'
      - name: Build with Gradle
        run: source ci.env && ./gradlew :${{ inputs.module_name }}:assembleDebug
      - name: Upload apk
        uses: actions/upload-artifact@v4.3.3
        with:
          path: ${{ github.workspace }}/${{ inputs.module_name }}/build/outputs/apk/debug/${{ inputs.module_name }}-debug.apk
          name: ${{ inputs.module_name }}-debug.apk # Also parameterize the artifact name itself for clarity
