name: gtd-release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build-apk.yml
    secrets: inherit
  release:
    needs: build
    runs-on: ubuntu-latest
    environment: main
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          draft: false
          artifacts: ${{ github.workspace }}/gtd-debug.apk
