name: gtd-fishfood

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17.0.10'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :gtd:assembleDebug
      - name: Upload apk
        uses: actions/upload-artifact@v4.3.3
        with:
          path: ${{ github.workspace }}/gtd/build/outputs/apk/debug/app-debug.apk