name: PR check

on:
  pull_request_target:
    branches: [ main ]

jobs:
  verify-gtd-compiles:
    uses: ./.github/workflows/build-apk.yml
    secrets: inherit
    with:
      module_name: gtd
  verify-linkshift-compiles:
    uses: ./.github/workflows/build-apk.yml
    secrets: inherit
    with:
      module_name: linkshift
